// <auto-generated />
namespace SCORM1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class uno5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uno5));
        
        string IMigrationMetadata.Id
        {
            get { return "202111191258137_uno5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
