// <auto-generated />
namespace SCORM1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Edutubercampocliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edutubercampocliente));
        
        string IMigrationMetadata.Id
        {
            get { return "202201261829251_Edutuber-campocliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
